Updated backup cron

diff --git a/images/db/defaults/usr/bin/backup b/images/db/defaults/usr/bin/backup
--- a/images/db/defaults/usr/bin/backup
+++ b/images/db/defaults/usr/bin/backup
@@ -1,4 +1,12 @@
 #!/bin/bash
+
+_LOG=/var/log/backup
+#set -x
+
+{
+
+. /etc/environment
+
 _PATH=/var/migasfree/dump
 
 DUMP_FILE="$1"
@@ -11,8 +19,15 @@ fi
 mkdir -p $_PATH || :
 
 export PGPASSWORD=$POSTGRES_PASSWORD
-echo "$(date -u) DUMP Database:  $POSTGRES_HOST:$POSTGRES_PORT $POSTGRES_DB to $_PATH/$DUMP_FILE ..."   >> $_PATH/backup.log 2>&1
-pg_dump -h $POSTGRES_HOST -p $POSTGRES_PORT $POSTGRES_DB -U $POSTGRES_USER > $_PATH/$DUMP_FILE
+echo "Time zone: $TZ"
+echo "$(date) Dump database to $_PATH/$DUMP_FILE ..."
 
-echo "$(date -u) DUMP done"  >> $_PATH/backup.log 2>&1
-echo ""  >>  $_PATH/backup.log 2>&1
+$(/usr/bin/which pg_dump) -h $POSTGRES_HOST -p $POSTGRES_PORT $POSTGRES_DB -U $POSTGRES_USER > $_PATH/$DUMP_FILE
+
+if [ $? = 0 ]; then
+  echo "$(date) Done!"
+else
+  echo "$(date) ERROR !!! "
+fi
+
+} 2>&1 | tee $_LOG
diff --git a/images/db/defaults/usr/bin/restore b/images/db/defaults/usr/bin/restore
--- a/images/db/defaults/usr/bin/restore
+++ b/images/db/defaults/usr/bin/restore
@@ -1,6 +1,7 @@
 #!/bin/bash
-
+#set -x
 _PATH=/var/migasfree/dump
+_LOG=/var/log/restore
 
 DUMP_FILE="$1"
 
@@ -9,13 +10,16 @@ then
     DUMP_FILE=migasfree.sql
 fi
 
-echo "Restore '$DUMP_FILE' dump. "
-ls  -la $_PATH/$DUMP_FILE
 
-read -p "Are you sure [y/N]? "
-echo
+{
 
-if [[ $REPLY =~ ^[Yy]$ ]] ; then
+  echo "Restore '$DUMP_FILE' dump. "
+  ls  -la $_PATH/$DUMP_FILE
+
+  read -p "Are you sure [yes/N]? "
+  echo
+
+  if [[ $REPLY = "yes" ]] ; then
 
     ps aux|grep pg_dump > /dev/null
     if [ $? = 1 ] ; then
@@ -23,20 +27,24 @@ if [[ $REPLY =~ ^[Yy]$ ]] ; then
        exit 1
     fi
 
+    echo "Time zone: $TZ"
+
     echo "$POSTGRES_HOST:$POSTGRES_PORT:$POSTGRES_DB:$POSTGRES_USER:$POSTGRES_PASSWORD" > ~/.pgpass
     chmod 0600 ~/.pgpass
 
-    echo "$(date -u) Drop Database: $POSTGRES_DB ..."   >> $_PATH/restore.log 2>&1
+    echo "$(date) Drop Database: $POSTGRES_DB ..."
     echo "DROP DATABASE $POSTGRES_DB;" | su postgres -c psql -
 
-    echo "$(date -u) Create BD ..." >> $_PATH/restore.log 2>&1
+    echo "$(date) Create BD ..."
     su postgres -c "createdb --no-password -E utf8 $POSTGRES_DB"
 
-    echo "$(date -u) Restore BD ..." >> $_PATH/restore.log 2>&1
+    echo "$(date) Restore BD ..."
     su postgres -c "psql --no-password -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -f $_PATH/$DUMP_FILE" -
+    if [ $? = 0 ] ; then
+      echo "$(date) Done."
+    else
+      echo "$(date) ERROR !!!"
+    fi
 
-
-    echo "$(date -u) Done." >> $_PATH/restore.log 2>&1
-    echo "" >> $_PATH/restore.log 2>&1
-
-fi
+  fi
+} 2>&1 | tee $_LOG
